version: "1.0"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: go_api
    restart: always
    ports:
      - "8080:8080"
      - "40000:40000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "apparmor=unconfined"

volumes:
  mysql_data:
